version: "3.2"
services:
    frontend:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ./:/usr/share/nginx/html
        ports:
            - "80:80"